### ISSUE TITLE
Multiple Timers

### ISSUE THREAD

**Issue by davidcralph** [ViciousSquid/ShowTime#1]
Hi!

Thank you for making this software. I had a feature idea - it'd be nice to be able to run multiple timers in an event. For example, if there was a series of acts, or sections, the user could set them all in advance and then start them when necessary.

Implementation idea would be as follows:
- List of timers with order, rename, change length, delete
- Export/import lists to a file

Perhaps, you could add the name of the timer as an option to be shown on the monitor as well 🙂 Or even a custom alert for when the act is out of time?

**Comment by ViciousSquid** [comment]
Hi!  Thanks for your message!  I'm learning as I go and I'll try your suggestion! If you have thoughts for how this could be done, please feel free to let me know.

**Comment by ViciousSquid** [comment]
I wrote this tool because I'm a sound engineer and I have to run back to the stage when an act finishes, so I get the timer ready at the same time as I do the snake box patches. I think a good way to meet you in the middle would be to have the HTTP server communicate in both directions. Thanks for your suggestion I will seriously try to do something!

**Comment by davidcralph** [comment]
Whilst I can't say it's the best method (not entirely sure to be honest), what I would do is have it read from a JSON.

I noticed the constants are stored separately but it'd be nice if they could be changed in built copies as well, so potentially a JSON or a ini could be used?

Hypothetical example for timer storage:
```js
// Example Project.st
{
  // shown as project name
  "project": "Example",
  // order of array is order of which things are displayed
  "timers": [
   {
     "name": "Act #1", // shown optionally on top, but also in list
     "length": 900000 // 15min, hopefully
      // optional settings for colours per one, message on time up etc
   }
  ]
}

```

**Comment by ViciousSquid** [comment]
Thanks for this!

On a separate note, I've been up all night working on this and wondered if you'd be interested in helping?

https://github.com/ViciousSquid/Adventure

**Comment by ViciousSquid** [comment]
An extremely simple way to accomplish your need for multiple timers in the mean-time is to just launch multiple instances of the timer

**Comment by ViciousSquid** [comment]
I gave your code to Claude 3 Opus and it was very happy to suggest changes which I have tested and implemented in v1.03

The application will now display a list of timers loaded from the config.json file, and the user can switch between them using the "<" and ">" buttons.

All hail Claude

**Comment by ViciousSquid** [comment]
By the way 900000 seconds is 15000 minutes (250hrs) lol
Timers default to 900 seconds (15 mins) by default in the json, best wishes x

**Comment by ViciousSquid** [comment]
Thanks for your sample code!!

The application will now display a list of timers loaded from the config.json file, and the user can switch between them using the "<" and ">" buttons.

The web client remains unchanged and continues to show Counter 1 only.
